options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'node:20'
    entrypoint: bash
    env:
      - DATABASE_URL=projects/tomochat-464710/secrets/DATABASE_URL:latest
    args:
      - -c
      - |
          echo "DATABASE_URL is $DATABASE_URL"
          npm ci
          npx prisma migrate deploy

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - buildx
      - build
      - --platform=linux/amd64
      - --tag
      - europe-west4-docker.pkg.dev/tomochat-464710/tomochat-repo/tomochat-be
      - --push
      - .

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - tomochat-be
      - --image
      - europe-west4-docker.pkg.dev/tomochat-464710/tomochat-repo/tomochat-be
      - --region
      - europe-west4
      - --platform
      - managed
      - --allow-unauthenticated
      - --add-cloudsql-instances
      - tomochat-464710:europe-west4:tomochat-db
      - --set-secrets
      - DATABASE_URL=projects/tomochat-464710/secrets/DATABASE_URL:latest