options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: node:20
    entrypoint: bash
    secretEnv: ['DATABASE_URL']
    args:
      - -c
      - |
        npm ci

  - name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - build
      - --platform=linux/amd64
      - --tag
      - europe-west4-docker.pkg.dev/$PROJECT_ID/tomochat-repo/tomochat-be
      - --push
      - .

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gcloud
      - run
      - deploy
      - tomochat-be
      - --image
      - europe-west4-docker.pkg.dev/$PROJECT_ID/tomochat-repo/tomochat-be
      - --region
      - europe-west4
      - --platform
      - managed
      - --allow-unauthenticated
      - --add-cloudsql-instances
      - tomochat-464710:europe-west4:tomochat-db
      - --set-secrets
      - DATABASE_URL=DATABASE_URL:latest

availableSecrets:
  secretManager:
    secrets:
      - versionName: projects/995534968592/secrets/DATABASE_URL/versions/1
        env: DATABASE_URL