# cloudbuild.yaml

substitutions:
  _SERVICE_NAME: tomochat-be
  _REGION: europe-west4
  _REPO: tomochat-repo
  _INSTANCE_CONNECTION_NAME: tomochat-464710:europe-west4:tomochat-db

steps:
  # Install deps & run Prisma migrate
  - name: 'node:20'
    entrypoint: bash
    env:
      - 'DATABASE_URL=postgresql://<user>:<password>@localhost:5432/<dbname>?host=/cloudsql/${_INSTANCE_CONNECTION_NAME}'
    secretEnv: ['DATABASE_URL']
    args:
      - -c
      - |
        npm ci
        npx prisma migrate deploy

  # Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'buildx', 'build',
        '--platform=linux/amd64',
        '--tag', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}',
        '--push',
        '.'
      ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud', 'run', 'deploy', '${_SERVICE_NAME}',
        '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}',
        '--region', '${_REGION}',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--add-cloudsql-instances', '${_INSTANCE_CONNECTION_NAME}',
        '--set-secrets', 'DATABASE_URL=DATABASE_URL:latest'
      ]

availableSecrets:
  secretManager:
    secrets:
      - versionName: projects/tomochat-464710/secrets/DATABASE_URL/versions/latest
        env: DATABASE_URL