import { AiResponse, supportedLanguage } from "./types";

const samples: Partial<Record<supportedLanguage, AiResponse[]>> = {
  "nl-NL": [
    {
      isMessageOk: true,
      original: "Ik denk dat ik straks naar huis ga.",
      fixedMessage: "",
      fixLogic: "",
      translated: "",
    },
    {
      isMessageOk: false,
      original: "I guess I go later.",
      fixedMessage: "Ik denk dat ik later ga.",
      fixLogic: "translated to Dutch",
      translated: "I guess I go later.",
    },
    {
      isMessageOk: false,
      original: "Ik heb eten gisteren.",
      fixedMessage: "Ik heb gisteren gegeten.",
      fixLogic: "corrected verb and word order",
      translated: "I ate yesterday.",
    },
    {
      isMessageOk: false,
      original: "Ik wil go naar het park.",
      fixedMessage: "Ik wil naar het park gaan.",
      fixLogic: "translated verb 'go'",
      translated: "I want to go to the park.",
    },
  ],
  "fr-FR": [
    {
      isMessageOk: true,
      original: "Je vais faire les courses maintenant.",
      fixedMessage: "",
      fixLogic: "",
      translated: "",
    },
    {
      isMessageOk: false,
      original: "I believe it's fine.",
      fixedMessage: "Je crois que c'est bon.",
      fixLogic: "translated to French",
      translated: "I believe it's fine.",
    },
    {
      isMessageOk: false,
      original: "Je suis tired aujourd’hui.",
      fixedMessage: "Je suis fatigué aujourd’hui.",
      fixLogic: "translated 'tired'",
      translated: "I am tired today.",
    },
    {
      isMessageOk: false,
      original: "Demain je aller la plage.",
      fixedMessage: "Demain, je vais à la plage.",
      fixLogic: "fixed verb and preposition",
      translated: "Tomorrow I go to the beach.",
    },
  ],
  "de-DE": [
    {
      isMessageOk: true,
      original: "Ich bin heute sehr müde.",
      fixedMessage: "",
      fixLogic: "",
      translated: "",
    },
    {
      isMessageOk: false,
      original: "I think I go home now.",
      fixedMessage: "Ich denke, ich gehe jetzt nach Hause.",
      fixLogic: "translated to German",
      translated: "I think I go home now.",
    },
    {
      isMessageOk: false,
      original: "Ich bin happy heute.",
      fixedMessage: "Ich bin heute glücklich.",
      fixLogic: "translated 'happy' and word order",
      translated: "I am happy today.",
    },
    {
      isMessageOk: false,
      original: "Ich habe gegessen ein Apfel.",
      fixedMessage: "Ich habe einen Apfel gegessen.",
      fixLogic: "corrected word order and article",
      translated: "I ate an apple.",
    },
  ],
  "es-ES": [
    {
      isMessageOk: true,
      original: "Voy a salir con mis amigos.",
      fixedMessage: "",
      fixLogic: "",
      translated: "",
    },
    {
      isMessageOk: false,
      original: "I think it's going to rain.",
      fixedMessage: "Creo que va a llover.",
      fixLogic: "translated to Spanish",
      translated: "I think it's going to rain.",
    },
    {
      isMessageOk: false,
      original: "Yo está muy feliz.",
      fixedMessage: "Yo estoy muy feliz.",
      fixLogic: "corrected verb form",
      translated: "I am very happy.",
    },
    {
      isMessageOk: false,
      original: "Mañana I will go al parque.",
      fixedMessage: "Mañana iré al parque.",
      fixLogic: "translated English part",
      translated: "Tomorrow I will go to the park.",
    },
  ],
  "it-IT": [
    {
      isMessageOk: true,
      original: "Vado a prendere un caffè.",
      fixedMessage: "",
      fixLogic: "",
      translated: "",
    },
    {
      isMessageOk: false,
      original: "I guess I'll see her.",
      fixedMessage: "Penso che la vedrò.",
      fixLogic: "translated to Italian",
      translated: "I guess I'll see her.",
    },
    {
      isMessageOk: false,
      original: "Io essere stanco oggi.",
      fixedMessage: "Io sono stanco oggi.",
      fixLogic: "corrected verb 'essere'",
      translated: "I am tired today.",
    },
    {
      isMessageOk: false,
      original: "Domani I go al mare.",
      fixedMessage: "Domani vado al mare.",
      fixLogic: "translated verb and fixed article",
      translated: "Tomorrow I go to the sea.",
    },
  ],
  "el-GR": [
    {
      isMessageOk: true,
      original: "Είναι πολύ ωραία μέρα σήμερα.",
      fixedMessage: "",
      fixLogic: "",
      translated: "",
    },
    {
      isMessageOk: false,
      original: "I believe it’s going to be a nice day.",
      fixedMessage: "Πιστεύω ότι θα είναι μια όμορφη μέρα.",
      fixLogic: "translated to Greek",
      translated: "I believe it’s going to be a nice day.",
    },
    {
      isMessageOk: false,
      original: "Θα go στο σπίτι μετά.",
      fixedMessage: "Θα πάω στο σπίτι μετά.",
      fixLogic: "translated verb 'go'",
      translated: "I will go home later.",
    },
    {
      isMessageOk: false,
      original: "Εγώ είναι πολύ κουρασμένος.",
      fixedMessage: "Εγώ είμαι πολύ κουρασμένος.",
      fixLogic: "corrected verb form",
      translated: "I am very tired.",
    },
  ],
  "pl-PL": [
    {
      isMessageOk: true,
      original: "Dzisiaj jest naprawdę zimno.",
      fixedMessage: "",
      fixLogic: "",
      translated: "",
    },
    {
      isMessageOk: false,
      original: "I want to buy chleb.",
      fixedMessage: "Chcę kupić chleb.",
      fixLogic: "translated English part",
      translated: "I want to buy bread.",
    },
    {
      isMessageOk: false,
      original: "Ja być zmęczony.",
      fixedMessage: "Jestem zmęczony.",
      fixLogic: "corrected verb structure",
      translated: "I am tired.",
    },
    {
      isMessageOk: false,
      original: "Idę do sklep tomorrow.",
      fixedMessage: "Jutro idę do sklepu.",
      fixLogic: "translated and reordered",
      translated: "Tomorrow I go to the store.",
    },
  ],
  "ro-RO": [
    {
      isMessageOk: true,
      original: "Mă duc la cumpărături acum.",
      fixedMessage: "",
      fixLogic: "",
      translated: "",
    },
    {
      isMessageOk: false,
      original: "I think she’s nice.",
      fixedMessage: "Cred că este drăguță.",
      fixLogic: "translated to Romanian",
      translated: "I think she’s nice.",
    },
    {
      isMessageOk: false,
      original: "Eu sunt fericit astăzi.",
      fixedMessage: "Sunt fericit astăzi.",
      fixLogic: "removed unnecessary pronoun",
      translated: "I am happy today.",
    },
    {
      isMessageOk: false,
      original: "Mâine I go la birou.",
      fixedMessage: "Mâine merg la birou.",
      fixLogic: "translated verb",
      translated: "Tomorrow I go to the office.",
    },
  ],
  "pt-PT": [
    {
      isMessageOk: true,
      original: "Hoje vou ao supermercado.",
      fixedMessage: "",
      fixLogic: "",
      translated: "",
    },
    {
      isMessageOk: false,
      original: "I believe it’s okay.",
      fixedMessage: "Acredito que está tudo bem.",
      fixLogic: "translated to Portuguese",
      translated: "I believe it’s okay.",
    },
    {
      isMessageOk: false,
      original: "Eu é cansado hoje.",
      fixedMessage: "Estou cansado hoje.",
      fixLogic: "corrected verb",
      translated: "I am tired today.",
    },
    {
      isMessageOk: false,
      original: "Amanhã I will visit meus pais.",
      fixedMessage: "Amanhã vou visitar os meus pais.",
      fixLogic: "translated verb and article",
      translated: "Tomorrow I will visit my parents.",
    },
  ],
  "uk-UA": [
    {
      isMessageOk: true,
      original: "Я сьогодні дуже втомлений.",
      fixedMessage: "",
      fixLogic: "",
      translated: "",
    },
    {
      isMessageOk: false,
      original: "I want to eat борщ.",
      fixedMessage: "Я хочу з’їсти борщ.",
      fixLogic: "translated English part",
      translated: "I want to eat borscht.",
    },
    {
      isMessageOk: false,
      original: "Я є студент.",
      fixedMessage: "Я студент.",
      fixLogic: "removed unnecessary verb",
      translated: "I am a student.",
    },
    {
      isMessageOk: false,
      original: "Завтра I go to market.",
      fixedMessage: "Завтра я піду на ринок.",
      fixLogic: "translated and reordered",
      translated: "Tomorrow I go to the market.",
    },
  ],
};

export const getSample = (languageCode: supportedLanguage) => {
  const responses = samples[languageCode];
  return responses.map((item) => JSON.stringify(item)).join("\n");
};
